### ISSUE TITLE
Option to grab from other countries

### ISSUE THREAD

**Issue by ldymek** [jbogers/ziggogo-epg#1]
Hello, 

id like to create list of countries using this EPG API, like Poland, Czech Republic, etc. I've managed to successfully grap PL content. Is it possible to add run parameter - country of API?

**Comment by jbogers** [comment]
Hi @ldymek , what changes to the URL(s) are needed for this? Adding an option should be possible, but I would like to have a confirmation on what URL(s) would or would not work.

**Comment by ldymek** [comment]
This works for Poland:

`        # Set up URL's statically
        self._epg_channel_list_url = (
            "https://prod.spark.upctv.pl/pol/web/linear-service/v2/channels?cityId=1&language=pl&productClass=Orion-DASH"
        )
        self._epg_segment_url = "https://static.spark.upctv.pl/pol/web/epg-service-lite/pl/pl/events/segments/{}"
        self._epg_detail_url = (
            "https://prod.spark.upctv.pl/pol/web/linear-service/v2/replayEvent/{}?returnLinearContent=true&language=pl"
        )`

**Comment by jbogers** [comment]
@ldymek , can you see if the changes from #2 work for you? Since I don't live in Poland (and cannot read Polish), my possibilities to check if the resulting XMLTV makes any sense is limited at best 😄

**Comment by ldymek** [comment]
Sure, I will test it, thanks!
