### ISSUE TITLE
Problem updating EPG data

### ISSUE THREAD

**Issue by wiljanp82** [jbogers/ziggogo-epg#4]
When Running the command: 

./ziggogoepg.py -f --channel-file channels.txt

I'll receive an error: 
Traceback (most recent call last):
  File "/home/user/ziggogo-epg-master/./ziggogoepg.py", line 151, in <module>
    exit(main())
  File "/home/user/ziggogo-epg-master/./ziggogoepg.py", line 140, in main
    grabber.grab(generate_only=args.generate_only)
  File "/home/user/ziggogo-epg-master/classes/ziggoepggrabber.py", line 149, in grab
    self._grab_programmes(channel_ids=channel_ids)
  File "/home/user/ziggogo-epg-master/classes/ziggoepggrabber.py", line 284, in _grab_programmes
    "title": event["title"],
KeyError: 'title'

As a fairly new user (+/- 1 week) i am using the latest version of the code. 
The OS i'am running this on is Debian Bullseye (11)

Is this a script error, or something i could fix myself?

Edit: i Think it has something to do with the channel names, after removing all unnecesary channels in the channels.txt the error  is gone.

**Comment by jbogers** [comment]
Sorry for the late reply. Due to personal circumstances I have been unable to work on this project for the last few months.
Do you still have the 'broken' channel name file? That way I can have a look at processing these names better and/or providing better error handling.

**Comment by jbogers** [comment]
I have observed the issue now too. I'm looking into a fix.

**Comment by jbogers** [comment]
I found the error. It was caused by a programme without a title. These are now ignored, as a title is a required field for XMLTV.
