### ISSUE TITLE
Guide one hour off

### ISSUE THREAD

**Issue by rhermsen** [jbogers/ziggogo-epg#7]
Thank you for creating and maintaining this EPG solution!!!

I installed ziggoogo-epg a little over a week ago and it is working well.
Today I was looking into the EPG guide in Kodi and discovered that the program time is off by one hour.
I assume this started due to the wintertime change last weekend, and scrolling back in the Guide to Saturday 28-Oct looks to confirm this.

I wonder if the daily updates gradually resolves this in the next 2-3 weeks?
Scrolling forward to the last entries on Sunday 12-Nov (RTL Weer - 19:55 uur) I see that this is still incorrect.

I have not found any incorrect time configuration.

**Comment by jbogers** [comment]
This EPG grabber is timezone aware and does grab the correct times.
This is actually a bug in Kodi and/or the Tvheadend plugin (or maybe Libreelec). I experience the same issue every DST change. This was happening in my setup too, even before I made this grabber.
If you look in Tvheadend you will see it reports the correct time and your recordings also happen on the right time.

Restarting Kodi corrects the issue on Kodi's end.

**Comment by rhermsen** [comment]
Thanks for looking into this soo quickly.
Indeed see correct times in TVH (on WSL) and a restart of Kodi corrected the Guide timestamps.

**Comment by jbogers** [comment]
I haven't been able to work on the code itself for a long time now, but answering questions/remarks is luckily easily done 😃
